index:
    path: /
    controller: App\Controller\MainController::index
files:
    path: /files
    controller: App\Controller\DateiController::index
files_upload:
    path: /files/upload
    controller: App\Controller\DateiController::upload
files_view:
    path: /files/view
    controller: App\Controller\DateiController::view
files_new:
    path: /files/new
    controller: App\Controller\DateiController::new
files_download:
    path: /files/download
    controller: App\Controller\DateiController::download
files_delete:
    path: /files/delete
    controller: App\Controller\DateiController::delete
files_rename:
    path: /files/rename
    controller: App\Controller\DateiController::rename
files_detail:
    path: /files/detail
    controller: App\Controller\DateiController::detail